#pragma once

// 2.2 emoji: the emoji this plugin knows, in the picker's order. QtCore only (unit-tested).
//
// The table (emojitable.inc) is generated by tools/emoji/gen_emoji.py from Python's offline
// unicodedata (names) and curated category lists, filtered to what Segoe UI Emoji draws in colour
// (tools/emoji_probe). Ids are indexes into this build's table: they are for this run only. What
// leaves the process (reactions on the wire, reactions.json) is the emoji's text or wireCode().
//
// Skin tones: a base emoji that has them is followed in the table by its five tone variants
// (light .. dark). The picker shows bases only; the tone selector picks a variant.

#include <QByteArray>
#include <QString>
#include <QStringList>
#include <QVector>

namespace emoji {

enum class Group { SmileysPeople = 0, AnimalsNature, FoodDrink, Activities, TravelPlaces, Objects, Symbols, Flags };
constexpr int kGroupCount = 8;
constexpr int kToneCount  = 5; // light, medium-light, medium, medium-dark, dark

int  count();
bool isValid(int id);

QString text(int id); // the fully qualified sequence ("❤️" with U+FE0F)
QString name(int id); // "grinning face"; tone variants "waving hand: medium skin tone"
QString keywords(int id); // extra search words ("lol", "+1", ...), space separated
Group   group(int id);
// A single code point that shows as text unless U+FE0F follows (Emoji_Presentation=No: ❤ © ☺ ...).
bool isTextDefault(int id);

bool hasTones(int id);            // a base followed by its kToneCount variants
int  tone(int id);                // 0: none, 1..kToneCount: a variant
int  baseOf(int id);              // a variant's base; id itself otherwise
int  withTone(int id, int tone);  // the variant of id's base with tone (0: the base); id when it has none
QString toneName(int tone);       // "medium skin tone"

// Base emoji (no tone variants) of a group, in display order.
QVector<int> members(Group group);
QString      groupName(Group group); // "Smileys & people", ...

// The table emoji with exactly this text, with or without its variation selectors; -1 if none.
int find(const QString& text);
// Emoji whose name or keywords start words matching every word of query (case-insensitive); best
// matches first, at most limit. Tone variants are not returned.
QVector<int> search(const QString& query, int limit = 200);

// ---- wire form (reactions) ----------------------------------------------------------------------
// Lower-case hex code points joined by '-', fully qualified: "1f44d", "2764-fe0f".
constexpr int kMaxWireCodePoints = 10;
QByteArray    wireCode(int id);
// The table emoji of a wire code (with or without variation selectors); -1 for a malformed or unknown one.
int  fromWireCode(const QByteArray& code);
bool isWireCode(const QByteArray& code); // grammar only (any emoji, known or not)

// ---- TeamSpeak's own emoticons --------------------------------------------------------------------
// TeamSpeak shows ":)" and friends as images named "emoticons:<file>" from its icon pack. The emoji
// that replaces one, and the code it was typed as (for copying); -1 / empty for unknown images.
int     forTeamSpeakEmoticon(const QString& imageName);
QString teamSpeakEmoticonCode(const QString& imageName);
// The emoji TeamSpeak's emoticon codes stand for (":)" -> 🙂), for tests and the docs.
QStringList teamSpeakEmoticonFiles();

// ---- for the segmenter ----------------------------------------------------------------------------
QString lookupKey(const QString& text);   // text without U+FE0F / U+FE0E
int     findKey(const QString& key);      // find() on a lookupKey()
bool    mayStart(uint codePoint);         // the first code point of some table emoji
int     maxKeyUnits();                    // longest lookupKey() in UTF-16 units

} // namespace emoji
