# tsmedia_embed_files(<output header> <symbol> <file> [<symbol> <file> ...])
#
# Turns binary files (PNG icons, ...) into C++ byte arrays at configure time:
#   static const unsigned char <symbol>[<size>] = {0x89,0x50,...};
# The bytes are exactly the file's bytes, so anything derived from them (a CRC-32 icon id, a hash)
# stays stable. The header is rewritten only when its content changes, and CMake re-runs the
# configure step when one of the files changes.
#
# Code that hands the data to Qt must copy it into an owned QByteArray first (never fromRawData):
# Qt may keep image data after the plugin DLL is unloaded.
function(tsmedia_embed_files output)
    set(args ${ARGN})
    list(LENGTH args count)
    math(EXPR odd "${count} % 2")
    if(count EQUAL 0 OR odd)
        message(FATAL_ERROR "tsmedia_embed_files: expected <symbol> <file> pairs")
    endif()

    set(content "// Generated by cmake/embed_files.cmake. Do not edit.\n#pragma once\n\n")
    while(args)
        list(POP_FRONT args symbol file)
        if(NOT IS_ABSOLUTE "${file}")
            set(file "${CMAKE_CURRENT_SOURCE_DIR}/${file}")
        endif()
        if(NOT EXISTS "${file}")
            message(FATAL_ERROR "tsmedia_embed_files: ${file} not found")
        endif()
        file(READ "${file}" hex HEX)
        string(LENGTH "${hex}" hexLength)
        math(EXPR size "${hexLength} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," all "${hex}")
        # 16 bytes ("0xNN," = 5 characters each) per line keeps the header readable.
        string(LENGTH "${all}" allLength)
        set(bytes "")
        set(offset 0)
        while(offset LESS allLength)
            string(SUBSTRING "${all}" ${offset} 80 line)
            string(APPEND bytes "    ${line}\n")
            math(EXPR offset "${offset} + 80")
        endwhile()
        file(RELATIVE_PATH shown "${CMAKE_CURRENT_SOURCE_DIR}" "${file}")
        string(APPEND content "// ${shown} (${size} bytes)\nstatic const unsigned char ${symbol}[${size}] = {\n${bytes}};\n\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")
    endwhile()

    file(WRITE "${output}.tmp" "${content}")
    configure_file("${output}.tmp" "${output}" COPYONLY) # only touches the header when it changed
    file(REMOVE "${output}.tmp")
endfunction()
